#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Dict, List


class AutoGenError(Exception):
    pass


def _post_json(url: str, payload: Dict[str, Any], timeout: int = 600) -> Dict[str, Any]:
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8", errors="ignore")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as e:
        raw = e.read().decode("utf-8", errors="ignore")
        try:
            msg = json.loads(raw).get("error", raw)
        except Exception:
            msg = raw or str(e)
        raise AutoGenError(f"ollama error: {msg}")
    except Exception as e:
        raise AutoGenError(f"ollama request failed: {e}")


def _safe_models(models: List[str]) -> List[str]:
    out = []
    seen = set()
    for m in models or []:
        s = str(m or "").strip()
        if not s or s in seen:
            continue
        seen.add(s)
        out.append(s)
    return out


def _extract_json_block(text: str) -> Dict[str, Any]:
    src = str(text or "").strip()
    if not src:
        raise AutoGenError("empty model response")
    try:
        return json.loads(src)
    except Exception:
        pass
    # Strip markdown code fences (```json ... ``` or ``` ... ```) if present.
    fence = re.search(r"```(?:json)?\s*([\s\S]*?)```", src, flags=re.I)
    if fence:
        try:
            return json.loads(fence.group(1).strip())
        except Exception:
            pass
    # Scan for every balanced top-level {...} block and try the largest ones
    # first (models sometimes prepend/append prose or example snippets that
    # contain their own smaller, unrelated brace pairs).
    candidates = []
    depth = 0
    start = None
    for i, ch in enumerate(src):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    candidates.append(src[start:i + 1])
                    start = None
    for block in sorted(candidates, key=len, reverse=True):
        try:
            parsed = json.loads(block)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            continue
    raise AutoGenError("no valid json object found in model response")


def _choose_model(model: str, allowed_models: List[str], default_model: str, warnings: List[str] | None = None) -> str:
    candidate = str(model or "").strip()
    allowed = set(allowed_models or [])
    if candidate and candidate in allowed:
        return candidate
    if warnings is not None:
        label = f"'{candidate}'" if candidate else "(none given)"
        warnings.append(f"model {label} not in ALLOWED_MODELS; substituted '{default_model}'")
    return default_model


def _normalize_agent(a: Dict[str, Any], allowed_models: List[str], default_model: str, objective: str, warnings: List[str] | None = None) -> Dict[str, Any] | None:
    name = str(a.get("name", "")).strip()
    model = _choose_model(str(a.get("model", "")).strip(), allowed_models, default_model, warnings)
    if not name or not model:
        return None
    mode = str(a.get("mode", "sequential")).strip().lower()
    if mode not in {"sequential", "parallel", "gated"}:
        mode = "sequential"
    system = str(a.get("system", "")).strip()
    if not system:
        system = (
            f"You are agent '{name}'. Execute the user's objective precisely and produce concrete, structured output. "
            f"Objective: {objective}"
        )
    role = str(a.get("role", "")).strip() or name.replace("_", " ").upper()
    agent_obj = str(a.get("objective", "")).strip() or objective
    tool_access = a.get("tool_access", [])
    if isinstance(tool_access, str):
        tool_access = [x.strip() for x in tool_access.split(",") if x.strip()]
    if not isinstance(tool_access, list):
        tool_access = []
    cleaned_tools = [str(x).strip() for x in tool_access if str(x).strip()]
    if not cleaned_tools:
        cleaned_tools = ["files_list", "archive_search", "run_pipeline"]
    memory_scope = str(a.get("memory_scope", "full")).strip().lower()
    if memory_scope not in {"full", "local", "none"}:
        memory_scope = "full"
    notes = str(a.get("notes", "")).strip() or "Auto-generated by ICI from user objective."
    return {
        "name": name,
        "model": model,
        "system": system,
        "mode": mode,
        "feeds": str(a.get("feeds", "scratchpad")).strip() or "scratchpad",
        "role": role,
        "objective": agent_obj,
        "tool_access": cleaned_tools,
        "memory_scope": memory_scope,
        "enabled": bool(a.get("enabled", True)),
        "notes": notes,
    }


def _normalize_step(s: Dict[str, Any], allowed_models: List[str], default_model: str, warnings: List[str] | None = None) -> Dict[str, Any] | None:
    model = _choose_model(str(s.get("model", "")).strip(), allowed_models, default_model, warnings)
    tpl = str(s.get("template", "")).strip() or "{{input}}"
    if not model:
        return None
    return {
        "model": model,
        "system": str(s.get("system", "")).strip(),
        "template": tpl,
        "step_name": str(s.get("step_name", "")).strip(),
        "description": str(s.get("description", "")).strip(),
        "run_mode": str(s.get("run_mode", "default")).strip() or "default",
        "assigned_agents": [str(x).strip() for x in (s.get("assigned_agents") or []) if str(x).strip()],
        "step_output_target": str(s.get("step_output_target", "scratchpad")).strip() or "scratchpad",
        "enabled": bool(s.get("enabled", True)),
        "notes": str(s.get("notes", "")).strip(),
    }


def build_autogen_plan(
    description: str,
    mode: str,
    models: List[str],
    ollama_base: str,
    planner_model: str = "",
) -> Dict[str, Any]:
    desc = str(description or "").strip()
    if not desc:
        raise AutoGenError("description is required")
    allowed_models = _safe_models(models)
    if not allowed_models:
        raise AutoGenError("no local models available")
    planner = str(planner_model or "").strip() or allowed_models[0]
    selected_mode = str(mode or "both").strip().lower()
    if selected_mode not in {"agents", "pipeline", "both", "links"}:
        selected_mode = "both"

    schema_hint = {
        "agents": [
            {
                "name": "string (required, non-empty)",
                "model": "string from ALLOWED_MODELS (required)",
                "system": "string (required, detailed)",
                "mode": "sequential|parallel|gated",
                "feeds": "scratchpad|chat",
                "role": "string (required)",
                "objective": "string (required)",
                "tool_access": ["tool_a", "tool_b"],
                "memory_scope": "full|local|none",
                "enabled": True,
                "notes": "string (required)",
            }
        ],
        "pipeline": [
            {
                "model": "string",
                "system": "string",
                "template": "{{input}}",
                "step_name": "string",
                "description": "string",
                "run_mode": "default|sequential|parallel|broadcast",
                "assigned_agents": ["agent-name"],
                "step_output_target": "scratchpad|chat",
                "enabled": True,
                "notes": "string",
            }
        ],
        "rationale": "short explanation",
    }

    prompt = (
        "Build a complete AMBER ICI configuration from the user objective.\n"
        "Choose the best models only from ALLOWED_MODELS.\n"
        "Decide how many agents and pipeline steps are required.\n"
        "Fill in all missing fields.\n"
        "No blank fields for agent objects: system, role, objective, tool_access, notes must be populated.\n"
        "Return JSON only.\n\n"
        f"MODE: {selected_mode}\n"
        f"ALLOWED_MODELS: {json.dumps(allowed_models)}\n"
        f"USER_OBJECTIVE:\n{desc}\n\n"
        f"OUTPUT_SCHEMA:\n{json.dumps(schema_hint)}\n"
    )

    req_payload = {
        "model": planner,
        "format": "json",
        "stream": False,
        "messages": [
            {
                "role": "system",
                "content": "You are a local orchestration architect. Output strict JSON only with no markdown."
            },
            {"role": "user", "content": prompt},
        ],
        "options": {"temperature": 0.2, "num_ctx": 8192},
    }
    try:
        data = _post_json(ollama_base.rstrip("/") + "/api/chat", req_payload, timeout=600)
    except AutoGenError:
        # Retry once with lighter context settings for slower local models.
        req_payload["options"] = {"temperature": 0.2, "num_ctx": 4096}
        data = _post_json(ollama_base.rstrip("/") + "/api/chat", req_payload, timeout=600)
    content = str((data.get("message") or {}).get("content", ""))
    parsed = _extract_json_block(content)
    raw_agents = parsed.get("agents") if isinstance(parsed.get("agents"), list) else []
    raw_pipeline = parsed.get("pipeline") if isinstance(parsed.get("pipeline"), list) else []

    warnings: List[str] = []
    agents = []
    for a in raw_agents:
        if isinstance(a, dict):
            na = _normalize_agent(a, allowed_models, allowed_models[0], desc, warnings)
            if na:
                agents.append(na)
    pipeline = []
    for s in raw_pipeline:
        if isinstance(s, dict):
            ns = _normalize_step(s, allowed_models, allowed_models[0], warnings)
            if ns:
                pipeline.append(ns)

    if selected_mode in {"agents"} and not agents:
        raise AutoGenError("planner returned no agents")
    if selected_mode in {"pipeline", "links"} and not pipeline:
        raise AutoGenError("planner returned no pipeline steps")
    if selected_mode == "both" and not (agents or pipeline):
        raise AutoGenError("planner returned empty configuration")

    return {
        "ok": True,
        "planner_model": planner,
        "mode": selected_mode,
        "agents": agents,
        "pipeline": pipeline,
        "rationale": str(parsed.get("rationale", "")).strip(),
        "warnings": warnings,
    }
